# This file was suppose to be Dockefile for production deployments without any extenstions

FROM node:16-alpine as builder

WORKDIR /app

COPY package.json .

RUN npm instal

COPY . .

CMD ["npm", "run", "build"]


FROM nginx

COPY --from=builder app/build  /usr/share/nginx/html # build is the actual directory which contains all the build files required to run an application


